# Week 01 — Basic Data Exploration and Cleaning using Pandas

**Dataset:** Ecommerce Shopping Dataset ([Kaggle](https://www.kaggle.com/datasets/anvitkumar/shopping-dataset))  
**Objective:** Load, explore, clean, and save a CSV dataset using Pandas.

## Step 0 — Create Combined Dataset from Individual CSVs

> **Run this only once.** The downloaded Kaggle dataset contains one CSV per product category.
> This step merges all of them into a single `Combined_dataset.csv`.
> If you already have `Combined_dataset.csv`, skip to Step 1.

In [37]:
import os
import glob
import pandas as pd
import numpy as np

# Path to the folder containing all individual category CSVs
CSV_FOLDER = 'raw_data'

# Find all CSV files except any existing combined file
all_csv_files = glob.glob(os.path.join(CSV_FOLDER, '*.csv'))
all_csv_files = [f for f in all_csv_files if 'Combined_dataset' not in f and 'cleaned' not in f]

print(f'Found {len(all_csv_files)} category CSV files:')
for f in sorted(all_csv_files):
    print(' ', os.path.basename(f))

Found 97 category CSV files:
  backpacks.csv
  bath-robe.csv
  bath-towels.csv
  bathroom-accessories.csv
  bedsheets.csv
  belts.csv
  bodysuit.csv
  boots.csv
  boxers.csv
  bra.csv
  bracelet.csv
  briefs.csv
  camisoles.csv
  candle-holders.csv
  caps.csv
  casual-shoes.csv
  chair-cover.csv
  clothing-set.csv
  clutches.csv
  co-ords.csv
  curtains-and-sheers.csv
  cutlery.csv
  dinnerware.csv
  dresses.csv
  duffel-bag.csv
  dungarees.csv
  dupatta.csv
  earrings.csv
  ethnic-dresses.csv
  face-moisturisers.csv
  face-wash-and-cleanser.csv
  flats.csv
  flip-flops.csv
  floor-mats--dhurries.csv
  formal-shoes.csv
  foundation.csv
  gloves.csv
  hair-accessory.csv
  hair-brush-and-comb.csv
  hair-cream-and-mask.csv
  hair-masks.csv
  handbags.csv
  headphones.csv
  heels.csv
  home-fragrance-set.csv
  innerwear-vests.csv
  jackets.csv
  jeans.csv
  jumpsuit.csv
  kurta-sets.csv
  kurtas.csv
  kurtis.csv
  lipstick.csv
  lounge-pants.csv
  lounge-shorts.csv
  lounge-tshirts.csv
  mangalsutra.csv
  mobile-accessories.csv
  night-suits.csv
  nightdress.csv
  outdoor-masks.csv
  palazzos.csv
  perfume-and-body-mist.csv
  pillow-covers.csv
  ring.csv
  runners.csv
  sandals.csv
  saree-blouse.csv
  sarees.csv
  scarves.csv
  shampoo-and-conditioner.csv
  shaving-essentials.csv
  sherwani.csv
  shirts.csv
  shorts.csv
  showpieces.csv
  skirts.csv
  sports-shoes.csv
  sunglasses.csv
  sweaters.csv
  sweatshirts.csv
  swim-tops.csv
  table-covers.csv
  thermal-bottoms.csv
  tights.csv
  tops.csv
  towel-set.csv
  track-pants.csv
  trolley-bag.csv
  trousers.csv
  trunk.csv
  tshirts.csv
  tunics.csv
  wall-art.csv
  wallets.csv
  watches.csv
  yoga-mats.csv

In [38]:
dfs = []

for filepath in sorted(all_csv_files):
    category_name = os.path.basename(filepath).replace('.csv', '')
    try:
        temp_df = pd.read_csv(filepath)
        temp_df['category'] = category_name   # tag each row with its source category
        dfs.append(temp_df)
    except Exception as e:
        print(f'  Skipped {category_name}: {e}')

# Merge all into one DataFrame
combined_df = pd.concat(dfs, ignore_index=True)

# Save
combined_df.to_csv('Combined_dataset.csv', index=False)

print(f'\nCombined dataset created!')
print(f'Total rows   : {len(combined_df):,}')
print(f'Total columns: {combined_df.shape[1]}')
print(f'Categories   : {combined_df["category"].nunique()}')

Combined dataset created!
Total rows   : 1,000
Total columns: 24
Categories   : 97

---
## Step 1 — Load the Combined Dataset

In [39]:
df = pd.read_csv('Combined_dataset.csv')

print('Dataset loaded successfully!')
print(f'Shape: {df.shape}')

Dataset loaded successfully!
Shape: (1000, 24)

## Step 2 — Explore the Data

In [40]:
# First and last 5 rows
print('--- HEAD ---')
display(df.head())
print('--- TAIL ---')
display(df.tail())

--- HEAD ---

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995.0,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899.0,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999.0,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675.0,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899.0,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

--- TAIL ---

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890.0,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900.0,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950.0,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295.0,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699.0,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [41]:
# Shape and column names
print('Shape:', df.shape)
print('\nColumns:', df.columns.tolist())

Shape: (1000, 24)

Columns: ['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

In [42]:
# Data types
df.dtypes

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

In [43]:
# Basic statistics for numeric columns
df.describe()

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

In [44]:
# Category breakdown — how many products per category?
category_counts = df['category'].value_counts()
print(f'Total categories: {len(category_counts)}')
print('\nTop 10 categories by product count:')
print(category_counts.head(10).to_string())

Total categories: 97

Top 10 categories by product count:
category
tops            122
dresses         100
shirts           97
jeans            57
sports-shoes     51
tshirts          39
earrings         34
sweaters         34
jackets          29
casual-shoes     23

## Step 3 — Handle Missing Values

In [45]:
# Check missing values per column
missing = df.isnull().sum()
missing_pct = (missing / len(df)) * 100

missing_df = pd.DataFrame({'Missing Count': missing, 'Missing %': missing_pct})
missing_df[missing_df['Missing Count'] > 0].sort_values('Missing %', ascending=False)

                     Missing Count  Missing %
videos                         781       78.1
what_customers_said            573       57.3
variations                     562       56.2
seller_name                    301       30.1
seller_information             301       30.1
discount                       121       12.1

In [46]:
# Drop columns with more than 50% missing values
cols_to_drop = missing_pct[missing_pct > 50].index.tolist()
print('Dropping columns with >50% missing:', cols_to_drop)
df.drop(columns=cols_to_drop, inplace=True)

Dropping columns with >50% missing: ['what_customers_said', 'videos', 'variations']

In [47]:
# Fill missing numeric values with column median
numeric_cols = df.select_dtypes(include=[np.number]).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

# Fill missing text values with 'Unknown'
categorical_cols = df.select_dtypes(include=['object', 'str']).columns
df[categorical_cols] = df[categorical_cols].fillna('Unknown')

print('Missing values after handling:', df.isnull().sum().sum())

Missing values after handling: 0

## Step 4 — Basic Operations (Filter & Select)

In [48]:
# Select key columns (only keep ones that exist)
key_cols = ['product_id', 'title', 'category', 'initial_price', 'final_price',
            'discount', 'rating', 'ratings_count', 'seller_name']
key_cols = [col for col in key_cols if col in df.columns]

df_filtered = df[key_cols].copy()
print('Working with columns:', key_cols)
df_filtered.head()

Working with columns: ['product_id', 'title', 'category', 'initial_price', 'final_price', 'discount', 'rating', 'ratings_count', 'seller_name']

,product_id,title,category,initial_price,final_price,discount,rating,ratings_count,seller_name
0,8376765,Lino Perros,backpacks,3995.0,"""₹3,995.00""",58.0,3.8,15,Unknown
1,9136281,Tommy Hilfiger,backpacks,2899.0,"""₹2,899.00""",35.0,4.5,67,Unknown
2,17633752,Lavie,backpacks,2999.0,"""₹2,999.00""",65.0,4.4,226,Unknown
3,1376949,F Gear,backpacks,1675.0,"""₹1,675.00""",52.0,4.4,1052,Unknown
4,13939916,MYTRIDENT,bath-robe,2899.0,"""₹2,899.00""",17.0,4.7,12,Unknown

In [49]:
# Filter: products with rating >= 4.0
if 'rating' in df_filtered.columns:
    high_rated = df_filtered[df_filtered['rating'] >= 4.0]
    print(f'Products with rating >= 4.0: {len(high_rated):,}')
    display(high_rated.head())

Products with rating >= 4.0: 615

,product_id,title,category,initial_price,final_price,discount,rating,ratings_count,seller_name
1,9136281,Tommy Hilfiger,backpacks,2899.0,"""₹2,899.00""",35.0,4.5,67,Unknown
2,17633752,Lavie,backpacks,2999.0,"""₹2,999.00""",65.0,4.4,226,Unknown
3,1376949,F Gear,backpacks,1675.0,"""₹1,675.00""",52.0,4.4,1052,Unknown
4,13939916,MYTRIDENT,bath-robe,2899.0,"""₹2,899.00""",17.0,4.7,12,Unknown
5,19851824,AVI Living,bath-towels,1399.0,"""₹1,399.00""",65.0,4.0,5,Unknown

In [50]:
# Filter: products with discount > 20%
if 'discount' in df_filtered.columns:
    discounted = df_filtered[df_filtered['discount'] > 20]
    print(f'Products with >20% discount: {len(discounted):,}')
    display(discounted.head())

Products with >20% discount: 941

,product_id,title,category,initial_price,final_price,discount,rating,ratings_count,seller_name
0,8376765,Lino Perros,backpacks,3995.0,"""₹3,995.00""",58.0,3.8,15,Unknown
1,9136281,Tommy Hilfiger,backpacks,2899.0,"""₹2,899.00""",35.0,4.5,67,Unknown
2,17633752,Lavie,backpacks,2999.0,"""₹2,999.00""",65.0,4.4,226,Unknown
3,1376949,F Gear,backpacks,1675.0,"""₹1,675.00""",52.0,4.4,1052,Unknown
5,19851824,AVI Living,bath-towels,1399.0,"""₹1,399.00""",65.0,4.0,5,Unknown

## Step 5 — Remove Duplicates

In [51]:
before = len(df_filtered)

# 1. Remove fully identical rows
df_filtered = df_filtered.drop_duplicates()
after_full = len(df_filtered)

# 2. Remove rows with duplicate product titles (keep first occurrence)
if 'title' in df_filtered.columns:
    df_filtered = df_filtered.drop_duplicates(subset='title', keep='first')
after_title = len(df_filtered)

print(f'Rows before          : {before:,}')
print(f'After full dedup     : {after_full:,}  (removed {before - after_full} exact duplicates)')
print(f'After title dedup    : {after_title:,}  (removed {after_full - after_title} duplicate titles)')

Rows before          : 1,000
After full dedup     : 1,000  (removed 0 exact duplicates)
After title dedup    : 454  (removed 546 duplicate titles)

## Step 6 — Create Derived Column: `total_amount`

In [52]:
# total_amount = final_price * ratings_count  (a rough proxy for product demand/revenue)
if 'final_price' in df_filtered.columns and 'ratings_count' in df_filtered.columns:
    df_filtered['total_amount'] = df_filtered['final_price'] * df_filtered['ratings_count']
    print('Derived column total_amount created.')
    display(df_filtered[['title', 'final_price', 'ratings_count', 'total_amount']].head(10))

Derived column total_amount created.

,title,final_price,ratings_count,total_amount
0,Lino Perros,"""₹3,995.00""",15,"""₹3,995.00""""₹3,995.00""""₹3,995.00""""₹3,995.00""""₹..."
1,Tommy Hilfiger,"""₹2,899.00""",67,"""₹2,899.00""""₹2,899.00""""₹2,899.00""""₹2,899.00""""₹..."
2,Lavie,"""₹2,999.00""",226,"""₹2,999.00""""₹2,999.00""""₹2,999.00""""₹2,999.00""""₹..."
3,F Gear,"""₹1,675.00""",1052,"""₹1,675.00""""₹1,675.00""""₹1,675.00""""₹1,675.00""""₹..."
4,MYTRIDENT,"""₹2,899.00""",12,"""₹2,899.00""""₹2,899.00""""₹2,899.00""""₹2,899.00""""₹..."
5,AVI Living,"""₹1,399.00""",5,"""₹1,399.00""""₹1,399.00""""₹1,399.00""""₹1,399.00""""₹..."
6,H&M,"""₹1,399.00""",42,"""₹1,399.00""""₹1,399.00""""₹1,399.00""""₹1,399.00""""₹..."
7,My Room,"""₹2,999.00""",10,"""₹2,999.00""""₹2,999.00""""₹2,999.00""""₹2,999.00""""₹..."
9,Story@home,"""₹2,199.00""",7,"""₹2,199.00""""₹2,199.00""""₹2,199.00""""₹2,199.00""""₹..."
11,Arrabi,"""₹865.00""",0,

## Step 7 — Save Cleaned Dataset

In [53]:
df_filtered.to_csv('ecommerce_cleaned.csv', index=False)

print('Saved: ecommerce_cleaned.csv')
print(f'Final shape: {df_filtered.shape}')

Saved: ecommerce_cleaned.csv
Final shape: (454, 10)

## Summary

| Step | Action | Result |
|------|--------|--------|
| 0 | Combined all category CSVs | Single `Combined_dataset.csv` |
| 1 | Loaded dataset | All rows across all categories |
| 2 | Explored data | Shape, dtypes, stats, category breakdown |
| 3 | Handled missing values | Dropped >50% null cols, filled rest |
| 4 | Filtered & selected | Key columns, high-rated & discounted products |
| 5 | Removed duplicates | Clean unique records |
| 6 | Created derived column | `total_amount = final_price * ratings_count` |
| 7 | Saved cleaned CSV | `ecommerce_cleaned.csv` |